### ISSUE TITLE
`vcr::vcr_test_path` issue from vcr v1.0.0

### ISSUE THREAD

**Issue by sckott** [DominikRafacz/deepdep#18]
With the latest version of `vcr` just up to CRAN I unfortunately caused breaking changes for some packages depending on `vcr`. The function `vcr_test_path` is the issue. The change to that function worked for some, but it apparently has broken other packages. 

We have a proposed fix at https://github.com/ropensci/vcr/pull/236 Can you install that fork `remotes::install_github("dpprdan/vcr@fix/test_path")` and see if that fixes the problem?

**Comment by DominikRafacz** [comment]
Thanks for informing me! I'm going to check it right now.

**Comment by sckott** [comment]
Thanks for checking it! We are still discussing this to make sure we're finding the best solution. Wait a bit longer and I'll get back to you. I plan to submit a fixed version soon - so you may not have to submit a new version yourself.  Apologies for this headache!

**Comment by DominikRafacz** [comment]
Okay, I've checked it. Sorry it took so long, I couldn't hurry up. Now it works as it supposed to.

**Comment by DominikRafacz** [comment]
Thanks, @sckott for solving it. I'dbe grateful if you could inform me that you have successfully uploaded the new version to CRAN by closing this issue so that I can deploy updated version of my package. I've made some changes to tests when figuring out in more detail how vcr works.

**Comment by sckott** [comment]
Okay, I will do that.

**Comment by sckott** [comment]
A new version of `vcr` is on CRAN https://cloud.r-project.org/web/packages/vcr/ - CRAN checks for your package should be fixed soon once they are using the new version of `vcr`.

**Comment by DominikRafacz** [comment]
Once again -- many thanks for your help! And thanks for a great and very useful package :)
