### ISSUE TITLE
Use same settings as base R package tools to compute dependencies

### ISSUE THREAD

**Issue by eddelbuettel** [DominikRafacz/deepdep#19]
`deepdep` defaults to the (deprecated, but still used) Depends as well as Imports.  

That is non-standard in the sense that base R package `tools` also use LinkingTo (which is equally 'non-negotiable') and optionally folds in Suggests and Enhances

Obviously we can add this by hand via `dependency_type=` but it is ... tedious.  I suggest to either expand the default and/or support use of `getOption()` with a fallback (which is a scheme I use and like in a few of my packages).  Happy to send a PR if that is seen as suitable.

The help for eg `tools::package_dependencie` has a good discussion, mimicking its options 'all' and 'most' and then 'strong' as the (new) default would be really nice:

>   which: a character vector listing the types of dependencies, a
          subset of ‘c("Depends", "Imports", "LinkingTo", "Suggests",
          "Enhances")’.  Character string ‘"all"’ is shorthand for that
          vector, character string ‘"most"’ for the same vector without
          ‘"Enhances"’, character string ‘"strong"’ (default) for the
          first three elements of that vector.

Thanks for creating the package.

**Comment by DominikRafacz** [comment]
Thanks for your suggestions! I think those improvements will be very useful.
