### ISSUE TITLE
Make 'stamp' optional?

### ISSUE THREAD

**Issue by eddelbuettel** [DominikRafacz/deepdep#20]
Currently the plot unconditionally adds a 'stamp':

https://github.com/DominikRafacz/deepdep/blob/7648251ac41cd09cab5c3e090f2589715da21ba8/R/plot_deepdep.R#L148-L150

While it is clear what motivates (hey we all want credit) it is a little ... 'loud'.  Would you consider hiding this behind a toggle that may well default to `TRUE` ?

**Comment by DominikRafacz** [comment]
Another good point from you!
Well, this package was created as a project for some course at my university, it was a training field for me and my colleagues and a lot of features that seemed reasonable then, are not so reasonable anymore...

**Comment by DominikRafacz** [comment]
Just to inform you, @eddelbuettel, together with @ErdaradunGaztea we are going to implement this and #19 through the weekend and udpate all this funny stuff like tests, docs and vignettes.

**Comment by eddelbuettel** [comment]
I just spent the few minutes this takes to patch the R file (all `plot_dependencies.*` variants) plus a `roxygen2` run, using a default of `TRUE` as before.  I can send you a PR if you want.

**Comment by DominikRafacz** [comment]
Your PR would be very welcome

**Comment by eddelbuettel** [comment]
I only gave it light testing so far but it seems to survive that :)    (Also, I think I saw that you good folks already works on following `tools` in its "classification" of dependencies and set but I didn't yet see that in the mainline :-/  Maybe I misread work in a branch for merged work.  One day...)
