### ISSUE TITLE
Move some Imports to Suggests

### ISSUE THREAD

**Issue by nathaneastwood** [DominikRafacz/deepdep#32]
We are considering using deepdep internally at work. We'd like to keep dependencies to a minimum and don't necessarily need the plotting features of this (great) package. Would it be possible to move the plotting packages to Suggests such that plotting is an optional part of what is offered by deepdep?

**Comment by ErdaradunGaztea** [comment]
Yep, that's doable, got a green light from Dominik; thanks for your (nomen omen) suggestion! Indeed, plotting is the reason for at least half of the Imports.

**Comment by ErdaradunGaztea** [comment]
And, for your information, such are the results of The Great Dependency Weakening.
Before:
![image](https://user-images.githubusercontent.com/32573962/146562913-90af1cef-7894-47cf-86c4-afb48b01278b.png)
After:
![image](https://user-images.githubusercontent.com/32573962/146562927-075f6a2e-ee32-4e42-b369-2e62ef342989.png)

**Comment by nathaneastwood** [comment]
_amazing_! Thanks so much!
