### ISSUE TITLE
Change colors in plots

### ISSUE THREAD

**Issue by kozaka93** [DominikRafacz/deepdep#5]
Could you change colors of arrows and labels in example plots because they can be prettier ;)

**Comment by hbaniecki** [comment]
Hi @kozaka93 
Thanks for your opinion. Can you propose some nicely looking color palette?

**Comment by hbaniecki** [comment]
Maybe `google` https://bookdown.org/ndphillips/YaRrr/more-colors.html

**Comment by kozaka93** [comment]
Looks better, also you can use palettes from `RColorBrewer` such as `Set1` or `Paired`.

**Comment by MatiFilozof** [comment]
We do now! (Just for edges, though)

Actually, it's ggplot object, so you can save it:
`g <- plot_dependencies("randomPackage")`
and just add scales you need, like `scale_edge_color_*` or `scale_fill_*`.
Let's say,
`g + scale_fill_brewer("Paired")`.

But, yeah, default palettes are not perfect yet.
